services:
  - type: web
    name: telegram-anime-bot
    env: python
    buildCommand: |
      pyenv install -s 3.12.6
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: TARGET_CHAT_ID
        sync: false
      - key: PORT
        value: 10000
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: anime-bot-db
          property: connectionString

databases:
  - name: anime-bot-db
    databaseName: anime_bot
    user: anime_bot_user
    plan: free
